# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("https://gimnasiomataro.provis.es/ActividadesColectivas/ClasesColectivasTimeLine?modelo=%7B%22Dia%22%3Anull%2C%22Mes%22%3Anull%2C%22Anio%22%3Anull%2C%22Public%22%3Afalse%2C%22startdatetime%22%3Anull%2C%22enddatetime%22%3Anull%2C%22zona%22%3Anull%2C%22monitor%22%3A0%2C%22agrupacion%22%3A0%2C%22actividad%22%3A0%2C%22ListaClases%22%3A%5B%5D%7D&integration=False&idClaseColectiva=0")
    self.driver.set_window_size(1366, 741)
    self.driver.find_element(By.CSS_SELECTOR, ".content-body").click()
    self.driver.find_element(By.ID, "btnLista").click()
    element = self.driver.find_element(By.ID, "dateAACC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dow:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Por Agrupación").click()
    element = self.driver.find_element(By.ID, "dateAACC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dow:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
    element = self.driver.find_element(By.LINK_TEXT, "Por Monitor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Por Actividad").click()
    self.driver.execute_script("window.scrollTo(0,880)")
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(16) .title").click()
    element = self.driver.find_element(By.ID, "dateAACC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dow:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
    element = self.driver.find_element(By.ID, "btnLista")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "btnLista").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.LINK_TEXT, "Por Monitor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "dateAACC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dow:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Por Actividad").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(8) .title").click()
    element = self.driver.find_element(By.ID, "dateAACC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dow:nth-child(7)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group").click()
    self.driver.find_element(By.ID, "16221").click()
    self.driver.find_element(By.ID, "btnCancelar").click()
  
